"""
Update tickers.txt with current S&P MidCap 400 (MDY) constituents.

Scrapes Wikipedia's list. Run this whenever the index rebalances
(quarterly — March, June, September, December).

Run in Pythonista: just tap Play.
"""

import os
import requests
from bs4 import BeautifulSoup


def scrape_mdy_tickers():
    """Scrape S&P MidCap 400 tickers from Wikipedia."""
    print("Fetching S&P MidCap 400 list from Wikipedia...")

    url = "https://en.wikipedia.org/wiki/List_of_S%26P_400_companies"
    headers = {"User-Agent": "Mozilla/5.0"}
    r = requests.get(url, headers=headers, timeout=15)

    soup = BeautifulSoup(r.text, "html.parser")

    # The first wikitable on the page is the constituents table
    table = soup.find("table", {"class": "wikitable"})
    if not table:
        print("ERROR: Could not find the table on Wikipedia.")
        return []

    tickers = []
    rows = table.find_all("tr")[1:]  # skip header row

    for row in rows:
        cells = row.find_all("td")
        if cells:
            ticker = cells[0].get_text(strip=True)
            # yfinance/Yahoo uses dashes instead of dots
            ticker = ticker.replace(".", "-")
            tickers.append(ticker)

    return sorted(set(tickers))


def save_tickers(tickers, path="tickers.txt"):
    """Write tickers to tickers.txt."""
    script_dir = os.path.dirname(os.path.abspath(__file__))
    full_path = os.path.join(script_dir, path)

    with open(full_path, "w") as f:
        f.write("# S&P MidCap 400 (MDY) constituents\n")
        f.write("# Auto-generated by update_tickers.py\n")
        f.write("#\n")
        for t in tickers:
            f.write(t + "\n")

    print(f"Saved {len(tickers)} tickers to {path}")


# ── Run ──────────────────────────────────────────

if __name__ == "__main__":
    tickers = scrape_mdy_tickers()

    if tickers:
        print(f"\nFound {len(tickers)} tickers:")
        print(", ".join(tickers[:20]) + "...")
        print()

        save_tickers(tickers)
        print("Done! Now run app.py to see prices.")
    else:
        print("No tickers found. Check your internet connection.")
